Feature/environment variables
Equipo-de-desarrollo-FCEN-UDEA/client_SIGA pull request #6
Opened 2024-11-21 21:44 UTC by estebandurangov

Se organiza para que la conexion con la API se realice mediante variables de ambiente.

2024-11-21 21:53 UTC, DavidTorres-sys approved these changes

2024-11-21 21:58 UTC, DavidTorres-sys requested changes

2024-11-21 21:58 UTC, DavidTorres-sys commented on src/app/voting/page.tsx
> +  console.log(apiUrl);
Eliminar

2024-11-21 21:58 UTC, DavidTorres-sys commented on src/core/services/api/voting/voteService.ts
> +        console.log("Datos enviados con éxito: ", responseData);
Eliminar

2024-11-21 22:16 UTC, DavidTorres-sys approved these changes

2024-11-22 15:47 UTC, alwos19 approved these changes

2024-11-22 15:47 UTC, merged