Feature/service voting
Equipo-de-desarrollo-FCEN-UDEA/client_SIGA pull request #8
Opened 2024-11-25 19:44 UTC by estebandurangov

2024-11-26 15:23 UTC, DavidTorres-sys approved these changes

2024-11-27 15:23 UTC, DavidTorres-sys commented on src/components/atoms/errors/ErrorCode.tsx
> +                    Acceso no autorizado
No seria mejor manejar el mensaje dinamicamente?

2024-11-27 15:53 UTC, DavidTorres-sys commented on src/components/atoms/errors/ErrorCode.tsx
No seria mejor crear un atomo de errorCode, que se le pase por lo props el status code y el message?

2024-11-28 02:40 UTC, DavidTorres-sys requested changes
No seria mejor crear un atomo de errorCode, que se le pase por lo props el status code y el message?

2024-11-28 13:45 UTC, FerneyMontoya6 commented on src/components/atoms/errors/ErrorCode.tsx
Estoy de acuerdo, eso sería una solución más genérica y por lo tanto más reutilizable.

2024-12-02 14:43 UTC, DavidTorres-sys approved these changes

2024-12-02 15:01 UTC, merged